export const ALERTS_STORE = 'ALERTS_STORE';
export const ANNOUNCEMENTS_STORE = 'ANNOUNCEMENTS_STORE';
export const FLAIRS_STORE = 'FLAIRS_STORE';
export const NOTIFICATIONS_STORE = 'NOTIFICATIONS_STORE';
export const SNACKBAR_STORE = 'SNACKBAR_STORE';
export const TABLES_STORE = 'TABLES_STORE';
export const USER_STORE = 'USER_STORE';

export const FIREBASE_USER_COOKIE = 'FIREBASER_USER_COOKIE';
