export const ALERTS_STORE = 'ALERTS_STORE';
export const APPLICATIONS_STORE = 'APPLICATIONS_STORE';
export const ANNOUNCEMENTS_STORE = 'ANNOUNCEMENTS_STORE';
export const FLAIRS_STORE = 'FLAIRS_STORE';
export const LOCALES_STORE = 'LOCALES_STORE';
export const NOTIFICATIONS_STORE = 'NOTIFICATIONS_STORE';
export const SNACKBAR_STORE = 'SNACKBAR_STORE';
export const TABLES_STORE = 'TABLES_STORE';
export const USER_STORE = 'USER_STORE';

export const LOCALE_STORAGE_KEY = 'LOCALE_STORAGE_KEY';

export const TABLE_CARD_DESCRIPTION_LENGTH = 192;
