export const MONGODB_COLLECTION_ANNOUNCEMENTS = 'announcement'
export const MONGODB_COLLECTION_ACCEPT_MESSAGES = 'accept-messages'
export const MONGODB_COLLECTION_APPLICATIONS = 'applications'
export const MONGODB_COLLECTION_FLAIRS = 'flairs'
export const MONGODB_COLLECTION_NOTIFICATIONS = 'notifications'
export const MONGODB_COLLECTION_TABLES = 'tables'
export const MONGODB_COLLECTION_USERS = 'users'
